apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ir-remote-ingress
  namespace: ir-remote
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - homeremote.wavefunctionlabs.com
      secretName: ir-remote-tls
  rules:
    - host: homeremote.wavefunctionlabs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ir-remote-svc
                port:
                  number: 80
