apiVersion: v1
kind: Secret
metadata:
  name: ir-remote-secrets
  namespace: ir-remote
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: "972253261833-d2qchfilsh4486o6668sik78fcirjt0k.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "REPLACE_WITH_GOOGLE_CLIENT_SECRET"
  SECRET_KEY: "30f70b9df98367f6bb98c9b378b777831810626bdf886cd179b6cdf2517a2bcc"
  PICO_DEVICE_TOKEN: "f80220a43fa69c6995bc34927631c9d5"
